### ISSUE TITLE
e2e test for UI extension

### ISSUE THREAD

**Issue by kkaempf** [rancher/highlander#79] opened 2024-04-09 15:23 UTC
An initial version of the [CAPI UI extension](https://github.com/rancher/capi-ui-extension) should be released soon.

This should be covered by E2E tests, covering the main features.

Marking as `kind/epic` since it should be broken-down to individual tests for each feature.

**Comment by alexander-demicev** [comment] 2024-07-16 14:30
duplicate of https://github.com/rancher/highlander/issues/41

**Closed by alexander-demicev** 2024-07-16 14:30 UTC
Labels: area/testing, kind/epic, area/ui
